const IMAGE = {
    ICON_MENU: require('../image/home-vector.png'),
    ICON_HOME_MENU: require('../image/home-menu-vector.png'),
    ICON_USER_DEFAULT: require('../image/plus.png'),
    ICON_ACCOUNT_MENU : require('../image/account-vector.png'),
    ICON_TAG_MENU : require('../image/tag.png'),
    ICON_CART_MENU : require('../image/cart-vector.png'),
    ICON_HEADER_MENU : require('../image/menu.png'),
    ICON_MENU_CART : require('../image/menu-cart.png'),
    ICON_SEARCH : require('../image/search-vector.png'),
    ICON_ARROW : require('../image/arrow-left-vector.png'),
    ICON_WISH : require('../image/wish.png'),
    ICON_DISCOVER : require('../image/discover-vector.png'),
    ICON_NOTIFICATION : require('../image/bell-vector.png'),
    ICON_LANGUAGE : require('../image/language-vector.png'),
    ICON_HELP : require('../image/question-vector.png'),
    ICON_INFO : require('../image/Info-vector.png'),
    ICON_POLICY : require('../image/policy-vector.png'),
    ICON_LOGOUT : require('../image/logout-vector.png'),
    ICON_MAP : require('../image/map-vector.png'),
    ICON_CREDIT_CARD : require('../image/credit-card-vector.png'),
    ICON_ORDER_LIST : require('../image/order-list-vector.png'),
    ICON_BOOKING : require('../image/booking-vector.png'),
    ICON_FAVOURITE : require('../image/heart-vector.png'),
    ICON_PENCIL : require('../image/pencil-vector.png'),
    ICON_EMAIL : require('../image/email-vector.png'),
    ICON_PHONE : require('../image/phone-vector.png'),
    ICON_CALENDER : require('../image/date-vector.png'),
    ICON_GENDER : require('../image/gender-vector.png'),
    ICON_APARTMENT : require('../image/apartment-vector.png'),
    ICON_ROUTE : require('../image/route-vector.png'),
    ICON_BUILDING : require('../image/building-vector.png'),
    ICON_MENU_DOT : require('../image/menu-dot-vector.png'),
    ICON_VISA_CARD : require('../image/visa-card-vector.png'),
    ICON_MASTERD_CARD : require('../image/masterd-card-vector.png'),
    ICON_CANCLE : require('../image/cancle-vector.png'),
    ICON_REPEAT : require('../image/repeat-order-vector.png'),
    ICON_LOCK : require('../image/lock-vector.png'),
    ICON_LOCK2 : require('../image/lock-vector2.png'),
    ICON_LOCK3 : require('../image/Lovk.png'),
    ICON_RECYCLE : require('../image/recycle-vector.png'),
    ICON_BOWL1 : require('../image/bowl1.png'),
    ICON_BOWL2 : require('../image/bowl2.png'),
    ICON_BOWL3 : require('../image/bowl3.png'),
    ICON_DELIVERY_MAN : require('../image/delivery-man-vector.png'),
    ICON_CLOCK : require('../image/clock-vector.png'),
    ICON_ORANGE_STAR : require('../image/start-orange-vector.png'),
    ICON_COUPON_BADGE : require('../image/coupon-badge.png'),
    ICON_COUPON_BADGE2 : require('../image/coupon-badge2.png'),
    ICON_INFO_FADE : require('../image/Info-vector-fade.png'),
    ICON_SHARE : require('../image/share-vector.png'),
    ICON_NON_SMOKING : require('../image/non-smoking-room.png'),
    ICON_ROOM_SERVICE : require('../image/room-service-vector.png'),
    ICON_BUS : require('../image/school-bus-vector.png'),
    ICON_SURFACE : require('../image/surface-vector.png'),
    ICON_DRYING : require('../image/drying.png'),
    ICON_FASHION : require('../image/fashion.png'),
    ICON_FORK : require('../image/fork.png'),
    ICON_WIFI : require('../image/wifi.png'),
}

export {IMAGE}