require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SwissMadeDirect' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'SwissMadeDirectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SwissMadeDirect-tvOS' do
  # Pods for SwissMadeDirect-tvOS

  target 'SwissMadeDirect-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
